module.exports = {
  TestUrl: process.env.TEST_URL || 'https://et-sya.aat.platform.hmcts.net',
  TestUrlForManageCaseAAT: process.env.TEST_MANAGE_CASE_URL || 'https://manage-case.aat.platform.hmcts.net',
  TestUrlForManageOrgAAT: process.env.TEST_MANAGE_ORG_URL || 'https://manage-org.aat.platform.hmcts.net',
  TestShowBrowserWindow: process.env.SHOW_BROWSER_WINDOW || true,
  TestsPathToRun: process.env.E2E_TEST_PATH || './**/*.js',
  TestReportFolder: process.env.E2E_OUTPUT_DIR || './functional-output/reports',
  TestEnvETUser: process.env.TEST_CASE_USERNAME || 'et.citizen1UI@testmail.com',
  TestEnvETPassword: process.env.TEST_CASE_PASSWORD || 'Nagoya0102',
  TestEnvETManageCaseUser: process.env.ET_CASEWORKER_USER_NAME || 'et.caseworker.5@hmcts.net',
  TestEnvETManageCasePassword: process.env.ET_CASEWORKER_PASSWORD || 'h8$w%vWk',
  TestEnvETLegalRepUser: process.env.TEST_LEGAL_REP_USERNAME || 'et.legalrep.1@gmail.com',
  TestEnvETLegalRepPassword: process.env.TEST_LEGAL_REP_PASSWORD || 'Nagoya0102',
  TestEnvETSuperUserUsername: process.env.TEST_MANAGE_ORG_SUPER_USERNAME || 'et.legalrep.superuser2@gmail.com',
  TestEnvETSuperUserPassword: process.env.TEST_MANAGE_ORG_SUPER_PASSWORD || 'Nagoya0102',
};
